// Reference distributions for legendary-feat detection (docs/combat-research.md §15).
// GENERATED by tools/feat-ref.mjs from 24 AI-commanded battles (29760 men) — do not edit by hand.
// kills[arm] = { p1: P(≥1 fighting kill in a battle | struck a blow in the press), r: geometric tail ratio P(≥k+1)/P(≥k), n: men who fought }
// surround[N] = P(a surviving man ever had ≥ N enemies on him at once)
export const REF = {
 "kills": {
  "spearmen": {
   "p1": 0.06517924291802457,
   "r": 0.12751677852348994,
   "n": 3989
  },
  "levy": {
   "p1": 0.04471195184866724,
   "r": 0.1,
   "n": 1163
  },
  "menatarms": {
   "p1": 0.074,
   "r": 0.1,
   "n": 1000
  },
  "archers": {
   "p1": 0.029411764705882353,
   "r": 0.1,
   "n": 102
  },
  "knights": {
   "p1": 0.1397139713971397,
   "r": 0.1,
   "n": 909
  },
  "pikemen": {
   "p1": 0.03317535545023697,
   "r": 0.1,
   "n": 422
  },
  "hobelars": {
   "p1": 0.00708502024291498,
   "r": 0.1,
   "n": 988
  },
  "crossbow": {
   "p1": 0.01818181818181818,
   "r": 0.1,
   "n": 55
  },
  "_all": {
   "p1": 0.06235512285581827,
   "r": 0.1,
   "n": 8628
  }
 },
 "surround": {
  "3": 0.10149783208513993,
  "4": 0.07543358297201419,
  "5": 0.05163579030350808,
  "6": 0.031533307055577456,
  "7": 0.018525817895151755,
  "8": 0.010396137169885692,
  "9": 0.00650374458021285,
  "10": 0.00428655892786756,
  "11": 0.0027098935750886873,
  "12": 0.0016752069373275522
 }
};
