// Builds the reference distributions for legendary-feat detection (js/sim/feat-ref.js, §15): runs whole
// AI-commanded battles and records, per arm, how many fighting kills each man made and how many enemies
// were ever on a man at once among those who lived. Run after any change to the combat maths.
//   node tools/feat-ref.mjs [battles=30]
import { Worker, isMainThread, parentPort } from "node:worker_threads";
import { availableParallelism } from "node:os";
import { writeFileSync } from "node:fs";

if (!isMainThread) {
  const { placeholderMap } = await import("../js/sim/map.js");
  const { readLand } = await import("../js/sim/landread.js");
  const { createWorld, addUnit, step, DT } = await import("../js/sim/world.js");
  const { combatSystem } = await import("../js/sim/combat.js");
  const { commandBattle } = await import("../js/sim/commander-ai.js");
  const { TERRAIN } = await import("../js/sim/terrain-types.js");
  const { armKey } = await import("../js/sim/arms.js");
  const map = placeholderMap(); map.land = readLand(map);
  const disp = ["defensive", "aggressive", "flanker", "inspiring"];
  parentPort.on("message", (seed) => {
    const w = createWorld({ map, terrain: TERRAIN, seed });
    w.systems.push(combatSystem);
    // (every other battle without bows: melee-heavy battles belong in the reference too, or a hard hand-to-hand
    // fight makes every second kill look legendary)
    const bows = seed % 2 === 1;
    const army = (team, x, y, face) => new Set([["spearmen", 160, -60, 0], ["levy", 140, 60, 0], ["menatarms", 80, 0, 30], [bows ? "archers" : "spearmen", 110, -150, 20], [team ? "hobelars" : "knights", 50, -230, -40], [team ? (bows ? "crossbow" : "spearmen") : "pikemen", 80, 230, 0]]
      .map(([arm, count, dx, dy]) => addUnit(w, { team, arm, count, x: x + dx, y: y + dy, facing: face, formation: arm === "archers" ? "line" : "deep" }).id));
    const A = { team: 0, units: army(0, 1300, 1400, 0), disposition: disp[seed % 4] }, B = { team: 1, units: army(1, 2500, 2300, Math.PI), disposition: disp[(seed >> 2) % 4] };
    for (let k = 0; k < 150 * 60 / DT; k++) { step(w); commandBattle(w, A); commandBattle(w, B); }
    const S = w.S, kills = {}, surround = {};
    for (let i = 0; i < S.n; i++) {
      const a = armKey(S.arm[i]); (kills[a] ||= []);
      // hand-to-hand kills of men still fighting, among the men who struck at least one blow in the press
      // (P(K ≥ k | he fought): a feat is judged against the men who were there, not against the reserves)
      if (S.atkTime[i] > 0 || S.mkills[i] > 0) kills[a][S.mkills[i]] = (kills[a][S.mkills[i]] || 0) + 1;
      if (S.alive[i]) surround[S.maxAtk[i]] = (surround[S.maxAtk[i]] || 0) + 1;
    }
    parentPort.postMessage({ kills, surround, n: S.n });
  });
} else {
  const battles = +(process.argv[2] || 30);
  const n = Math.min(availableParallelism(), battles);
  const out = []; let next = 1;
  await new Promise((resolve) => {
    for (let k = 0; k < n; k++) {
      const wk = new Worker(new URL(import.meta.url));
      wk.on("message", (m) => { out.push(m); if (process.stderr.isTTY) process.stderr.write(`\r${out.length}/${battles}`); if (next <= battles) wk.postMessage(next++); else wk.terminate(); if (out.length === battles) resolve(); });
      wk.postMessage(next++);
    }
  });
  // merge and fit: p1 = P(K ≥ 1); r from the mean of the conditional tail (geometric fit: E[K−1 | K ≥ 1] = r/(1−r))
  const K = {}, SUR = {}; let men = 0;
  for (const m of out) { men += m.n; for (const [a, h] of Object.entries(m.kills)) { K[a] ||= []; h.forEach((c, k) => { if (c) K[a][k] = (K[a][k] || 0) + c; }); } for (const [s, c] of Object.entries(m.surround)) SUR[s] = (SUR[s] || 0) + c; }
  const fit = (h) => { const tot = h.reduce((s, c) => s + (c || 0), 0), pos = tot - (h[0] || 0); if (!pos) return { p1: 0.5 / tot, r: 0.2, n: tot }; let m = 0; h.forEach((c, k) => { if (k >= 1 && c) m += (k - 1) * c; }); m /= pos; return { p1: pos / tot, r: Math.max(0.1, Math.min(0.9, m / (1 + m))), n: tot }; }; // (r floored at 0.1: a tail measured on a handful of killers must not make every third kill a legend)
  const kills = {}; const all = [];
  for (const [a, h] of Object.entries(K)) { kills[a] = fit(h); h.forEach((c, k) => { if (c) all[k] = (all[k] || 0) + c; }); }
  kills._all = fit(all);
  const alive = Object.values(SUR).reduce((s, c) => s + c, 0), surround = {};
  for (let N = 3; N <= 12; N++) { let c = 0; for (const [s, v] of Object.entries(SUR)) if (+s >= N) c += v; surround[N] = Math.max(0.5 / alive, c / alive); }
  const src = `// Reference distributions for legendary-feat detection (docs/combat-research.md §15).
// GENERATED by tools/feat-ref.mjs from ${battles} AI-commanded battles (${men} men) — do not edit by hand.
// kills[arm] = { p1: P(≥1 fighting kill in a battle | struck a blow in the press), r: geometric tail ratio P(≥k+1)/P(≥k), n: men who fought }
// surround[N] = P(a surviving man ever had ≥ N enemies on him at once)
export const REF = ${JSON.stringify({ kills, surround }, null, 1)};
`;
  writeFileSync(new URL("../js/sim/feat-ref.js", import.meta.url), src);
  console.log(`\nwrote js/sim/feat-ref.js from ${battles} battles, ${men} men`);
  for (const [a, f] of Object.entries(kills)) console.log(`${a.padEnd(10)} P(≥1 kill) ${(f.p1 * 100).toFixed(1)}%  tail ratio ${f.r.toFixed(2)}  → P(≥5) ${(f.p1 * f.r ** 4).toExponential(1)}  (n=${f.n})`);
  console.log("surround", JSON.stringify(surround));
}
